# Generated by Django 4.2 on 2023-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('location', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=50)),
                ('designer_profile', models.CharField(max_length=100)),
                ('designs_year', models.CharField(max_length=10)),
                ('project_title', models.CharField(max_length=30)),
                ('project_subtitle', models.CharField(max_length=20)),
                ('contact_title', models.CharField(max_length=30)),
                ('contact_subtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=20)),
                ('item_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='service/')),
                ('html_file', models.CharField(blank=True, max_length=100, null=True)),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('title', models.CharField(max_length=35)),
                ('title2', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=6)),
                ('banner', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('title', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('video_link', models.CharField(max_length=100)),
            ],
        ),
    ]
