# Generated by Django 4.2 on 2023-08-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='abouts/')),
                ('author_name', models.CharField(max_length=30)),
                ('author_title', models.CharField(max_length=20, null=True)),
                ('author_details', models.TextField(blank=True, null=True)),
                ('author_image', models.ImageField(upload_to='ceo/')),
                ('item_name', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=30)),
                ('background_image', models.ImageField(null=True, upload_to='background/')),
                ('work_sample_picture', models.ImageField(null=True, upload_to='abouts/')),
                ('year_of_company_experience', models.CharField(max_length=3, null=True)),
                ('circle_title_of_experience', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_link', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='', verbose_name='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_subtitle', models.CharField(max_length=50)),
                ('page_title', models.CharField(max_length=20)),
                ('page_background', models.ImageField(upload_to='background')),
                ('date', models.DateTimeField(null=True)),
                ('form_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_background', models.ImageField(upload_to='background/')),
                ('page_background', models.ImageField(upload_to='background/')),
                ('contact_title', models.CharField(max_length=40)),
                ('contact_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('image1', models.ImageField(null=True, upload_to='blog/')),
                ('image2', models.ImageField(null=True, upload_to='blog/')),
                ('image3', models.ImageField(null=True, upload_to='blog/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('desc2', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(max_length=200, null=True)),
                ('author_of_quote', models.CharField(max_length=30, null=True)),
                ('quote_icon', models.ImageField(null=True, upload_to='icon/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('image', models.ImageField(null=True, upload_to='projects/')),
                ('serial', models.IntegerField(null=True, unique=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('image2', models.ImageField(null=True, upload_to='projects/')),
                ('image3', models.ImageField(null=True, upload_to='projects/')),
                ('desc', models.TextField(null=True)),
                ('desc2', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=70)),
                ('profile', models.ImageField(upload_to='team_member/')),
                ('age', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('facebook', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('twitter', models.CharField(max_length=60)),
                ('skill', models.ManyToManyField(to='website.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('author_title', models.CharField(max_length=30)),
                ('quote', models.TextField(blank=True, null=True)),
                ('author_image', models.ImageField(upload_to='author/')),
            ],
        ),
        migrations.CreateModel(
            name='TopClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('thumb_no', models.CharField(max_length=2, null=True)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='info',
            name='about_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='blog_details_page_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='blog_details_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='blog_page_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='blog_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='footer_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='footer_image',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='info',
            name='footer_image2',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='info',
            name='footer_image3',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='info',
            name='latestNews_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_details_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_details_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='project_page_about_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_page_title_background',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_icon',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_image',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_image2',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='service_page_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='service_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='testimonial_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='testimonial_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_include',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_solution',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image2',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image3',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_logo',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_draft',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.latestnews'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
