# Generated by Django 4.2 on 2023-08-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_link', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='', verbose_name='clients/')),
            ],
        ),
    ]
