# Generated by Django 4.2 on 2023-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='team_details_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='team_details_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='team_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='team_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
