# Generated by Django 4.2 on 2023-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_latestnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='latestNews_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
