# Generated by Django 4.2 on 2023-08-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.blogcategory'),
        ),
    ]
