# Generated by Django 4.2 on 2023-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_info_latestnews_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='abouts/')),
                ('ceo_name', models.CharField(max_length=30)),
                ('ceo_details', models.TextField(blank=True, null=True)),
                ('ceo_image', models.ImageField(upload_to='ceo/')),
                ('item_name', models.CharField(max_length=30)),
                ('item_locatio', models.CharField(max_length=30)),
            ],
        ),
    ]
