# Generated by Django 4.2 on 2023-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_latestnews_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
