# Generated by Django 4.2 on 2023-08-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='item_locatio',
            new_name='item_location',
        ),
    ]
