# Generated by Django 4.2 on 2023-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_ceo_details_about_author_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='slider',
            name='item_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
