# Generated by Django 4.2 on 2023-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_info_error_page_subtitle_info_error_page_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='error_head',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
