# Generated by Django 4.2 on 2023-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_item_slider_item_location_slider_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
