# Generated by Django 4.2 on 2023-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_info_error_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='error_head',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
