# Generated by Django 4.2 on 2023-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_info_error_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='error_page_subtitle',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
