# Generated by Django 4.2 on 2023-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_background', models.ImageField(upload_to='background/')),
                ('page_background', models.ImageField(upload_to='background/')),
                ('contact_title', models.CharField(max_length=40)),
                ('contact_desc', models.TextField(max_length=150)),
            ],
        ),
    ]
