# Generated by Django 4.2 on 2023-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_contact_contact_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='circle_title_of_experience',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='work_sample_picture',
            field=models.ImageField(null=True, upload_to='abouts/'),
        ),
        migrations.AddField(
            model_name='about',
            name='year_of_company_experience',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
