# Generated by Django 4.2 on 2023-08-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_about_circle_title_of_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='circle_title_of_experience',
        ),
        migrations.RemoveField(
            model_name='about',
            name='year_of_company_experience',
        ),
    ]
