# Generated by Django 4.2 on 2023-08-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_project_picture1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='picture1',
        ),
    ]
