# Generated by Django 4.2 on 2023-08-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_about_circle_title_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='circle_title_of_experience',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='year_of_company_experience',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
