# Generated by Django 4.2 on 2023-08-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_project_picture1'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='item_desc',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
