# Generated by Django 4.2 on 2023-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_about_circle_title_of_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('author_title', models.CharField(max_length=30)),
                ('quote', models.TextField(blank=True, null=True)),
                ('author_image', models.ImageField(upload_to='author/')),
            ],
        ),
    ]
