# Generated by Django 4.2 on 2023-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='footer_image',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='info',
            name='footer_image2',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
    ]
