# Generated by Django 4.2 on 2023-08-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_info_footer_image_info_footer_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='footer_image3',
            field=models.ImageField(null=True, upload_to='footer/'),
        ),
    ]
