# Generated by Django 4.2 on 2023-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_video_quote_video_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('link', models.CharField(max_length=60)),
            ],
        ),
    ]
