# Generated by Django 4.2 on 2023-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_info_footer_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('si_no', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=70)),
                ('profile', models.ImageField(upload_to='team_member/')),
                ('age', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('facebook', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('twitter', models.CharField(max_length=60)),
                ('skill', models.CharField(max_length=250)),
            ],
        ),
    ]
