# Generated by Django 4.2 on 2023-08-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_instagallery_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topclients',
            name='thumb_no',
        ),
    ]
