# Generated by Django 4.2 on 2023-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
