# Generated by Django 4.2 on 2023-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_topclients_thumb_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='top_client_icon',
            field=models.ImageField(default=1, upload_to='icon/'),
            preserve_default=False,
        ),
    ]
