# Generated by Django 4.2 on 2023-08-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_info_top_client_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topclients',
            name='thumb_no',
        ),
    ]
