# Generated by Django 4.2 on 2023-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_si_no_teammember_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image2',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sample_image3',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
