# Generated by Django 4.2 on 2023-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_topclients_thumb_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='project_background',
            field=models.ImageField(default=1, upload_to='background/'),
            preserve_default=False,
        ),
    ]
