# Generated by Django 4.2 on 2023-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_icon_service_service_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
