# Generated by Django 4.2 on 2023-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_info_testimonial_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='button_text',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
