# Generated by Django 4.2 on 2023-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_service_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='skill',
        ),
        migrations.AddField(
            model_name='teammember',
            name='skill',
            field=models.ManyToManyField(to='website.skill'),
        ),
    ]
