# Generated by Django 4.2 on 2023-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_skill_remove_teammember_skill_teammember_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='service_page_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='service_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_section_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_section_icon',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_section_image',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_section_image2',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_section_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_include',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_solution',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_draft',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
