# Generated by Django 4.2 on 2023-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_about_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='land',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
