# Generated by Django 4.2 on 2023-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_slider_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='item_image',
            field=models.ImageField(null=True, upload_to='slider/'),
        ),
    ]
