# Generated by Django 4.2 on 2023-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_info_service_page_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about_section_background',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_section_icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_section_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_section_image2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='about_section_title',
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_icon',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_image',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_image2',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='info',
            name='service_about_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
