# Generated by Django 4.2 on 2023-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_remove_service_about_section_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='project_page_about_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='project_page_title_background',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
