# Generated by Django 4.2 on 2023-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_slider_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_shape',
            field=models.ImageField(null=True, upload_to='shape/'),
        ),
    ]
