# Generated by Django 4.2 on 2023-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_info_project_page_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='testimonial_page_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='testimonial_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
