# Generated by Django 4.2 on 2023-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_slider_slider_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_shape',
        ),
        migrations.AddField(
            model_name='info',
            name='slider_shape',
            field=models.ImageField(null=True, upload_to='shape/'),
        ),
    ]
