# Generated by Django 4.2 on 2023-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_info_testimonial_page_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
    ]
