# Generated by Django 4.2 on 2023-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_slider_slider_shape_info_slider_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='item_no',
        ),
    ]
