# Generated by Django 4.2 on 2023-08-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_slider_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='serial',
        ),
    ]
