# Generated by Django 4.2 on 2023-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_teammember_skill_teammember_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='skill',
        ),
        migrations.AddField(
            model_name='teammember',
            name='skill',
            field=models.ManyToManyField(null=True, to='website.skill'),
        ),
    ]
