# Generated by Django 4.2 on 2023-08-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_teammember_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='contact_page_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
