# Generated by Django 4.2 on 2023-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_remove_teammember_skill_teammember_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='blog_page_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='blog_page_title_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
