# Generated by Django 4.2 on 2023-08-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_info_contact_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_page_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
