# Generated by Django 4.2 on 2023-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_info_blog_page_title_info_blog_page_title_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_subtitle', models.CharField(max_length=50)),
                ('page_title', models.CharField(max_length=20)),
                ('page_background', models.ImageField(upload_to='background')),
                ('date', models.DateField(max_length=10)),
                ('time', models.TimeField(max_length=10)),
                ('form_title', models.CharField(max_length=50)),
            ],
        ),
    ]
