# Generated by Django 4.2 on 2023-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_info_about_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='service_about_desc',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
