# Generated by Django 4.2 on 2023-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_comingsoon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoon',
            name='time',
        ),
        migrations.AlterField(
            model_name='comingsoon',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
