# Generated by Django 4.2 on 2023-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_info_service_about_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='service_page_section_background',
            field=models.ImageField(null=True, upload_to='background/'),
        ),
    ]
