# Generated by Django 4.2 on 2023-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_info_service_page_section_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_quote_icon',
            field=models.ImageField(null=True, upload_to='icon/'),
        ),
    ]
