# Generated by Django 4.2 on 2023-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
