# Generated by Django 4.2 on 2023-08-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_remove_comment_user_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='message',
        ),
    ]
