# Generated by Django 4.2 on 2023-08-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_rename_comment_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
    ]
